name: balloon_burst
description: A balloon popping game.

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.8.1

  tapjunkie_engine:
    git:
      url: https://${ENGINE_TOKEN}@github.com/Sinhuej/tapjunkie_engine.git
      ref: main
