- name: Get Flutter packages
        working-directory: .
        run: flutter pub get

      - name: Build APK
        working-directory: .
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: balloon-burst-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build AAB
        working-directory: .
        run: flutter build appbundle --release

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: balloon-burst-aab
          path: build/app/outputs/bundle/release/app-release.aab

